import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import Layout from '@/components/common/Layout'
import { GlobalStyles } from '@/styles/globalStyle'
import StyledComponentsRegistry from '@/libs/registry'
import QueryClientProvider from '@/components/common/provider/queryClientProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <StyledComponentsRegistry>
          <QueryClientProvider>
            <Layout>{children}</Layout>
          </QueryClientProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
