import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import Layout from '@/components/common/Layout'
import { GlobalStyles } from '@/styles/globalStyle'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <GlobalStyles />
        <Layout>{children}</Layout>
      </body>
    </html>
  )
}
